.TH tictactoe 1 2022-03-15 GNU

.SH NAME
tictactoe \- tictactoe terminal game

.SH SYNOPSIS
.B tictactoe
[\fB\-c\fR]
[\fB\-p\fR]

.SH DESCRIPTION
.B tictactoe \- 
play tictactoe on the terminal

.SH USAGE
If called without args, start a human x human game.

.TP
.B \-\-help
displays help.
.TP
.B \-\-computer,\ \-c
start a human x computer game.
.TP
.B \-\-player,\ \-p
start a human x human game.
